{% set name = "gmpyinfr_dbutils" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmpyinfr_dbutils-{{ version }}.tar.gz
  sha256: 9d4bc081665055407acd437c7c776bcc3de81e02b2e75a87c095d2129180ea85

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pybind11 >=2.2.0
  run:
    - pybind11 >=2.2.0
    - pandas >=1.0.0
    - pyarrow >=3.0.0
    - python >={{ python_min }}
    - turbodbc ==4.1.2

test:
  imports:
    - gmpyinfr_dbutils
    - gmpyinfr_dbutils.db
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gmpyinfr-dbutils/
  summary: Infraestrutura dbutils python de uma equipe de Ciência de Dados
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anewmanvs
